name: Colcon Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: humble

      - name: Run Tests
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: avoid_obstacle_cpp
          import-token: ${{ secrets.REPO_TOKEN }}
          target-ros2-distro: humble

      - name: Upload Logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ros_ws/log
        if: always()
